import { Button, VerticalBox, StyleMetrics } from "std-widgets.slint";

export component AppWindow inherits Window {
    in property <string> code;
    in property <string> from_app;
    callback paste-code();
    always-on-top: true;
    no-frame: true;
    background: transparent;
    width: 200px;
    height: 108px;
    default-font-size: 13px;
    Rectangle {
        width: 100%;
        height: 100%;
        border-radius: 9px;
        background: StyleMetrics.dark-color-scheme ? black : white;
        VerticalBox {
            spacing: 10px;
            text := Text {
                vertical-stretch: 0;
                text: "1. 用鼠标左键点击验证码输入框\n2. 用 ⌘ + click 点击下方按钮";
            }
            Button {
                vertical-stretch: 1;
                text: "验证码：\{code} \n 来自\"\{from_app}\"";
                clicked => {
                    paste-code();
                }
            }
        }
    }
}
