import { Button, VerticalBox, StyleMetrics } from "std-widgets.slint";

export component AppWindow inherits Window {
    in property <string> paste_code_instruction;
    in property <string> verification_code_label;
    callback paste-code();
    callback mouse_move(length, length);
    always-on-top: true;
    no-frame: true;
    background: transparent;
    min-width: 200px;
    min-height: 108px;
    default-font-size: 13px;
    
    Rectangle {
        width: 100%;
        height: 100%;
        border-radius: 9px;
        background: StyleMetrics.dark-color-scheme ? black : white;
        // 插入 TouchArea 用于实现拖动功能
        TouchArea {
            // 使用 moved 事件更新窗口位置
            moved => {
                root.mouse_move(self.mouse-x - self.pressed-x, self.mouse-y - self.pressed-y);
            }

            VerticalBox {
                spacing: 10px;
                text := Text {
                    vertical-stretch: 0;
                    text: paste_code_instruction;
                }
                Button {
                    vertical-stretch: 1;
                    text: verification_code_label;
                    clicked => {
                        paste-code();
                    }
                }
            }
        }
    }
}
