import { Button, VerticalBox, StyleMetrics } from "std-widgets.slint";

export component AppWindow inherits Window {
    in property <string> code;
    in property <string> from_app;
    in property <string> paste_code_instruction;
    in property <string> verification_code;
    in property <string> from_label;
    callback paste-code();
    always-on-top: true;
    no-frame: true;
    background: transparent;
    width: 200px;
    height: 108px;
    default-font-size: 13px;
    Rectangle {
        width: 100%;
        height: 100%;
        border-radius: 9px;
        background: StyleMetrics.dark-color-scheme ? black : white;
        VerticalBox {
            spacing: 10px;
            text := Text {
                vertical-stretch: 0;
                text: paste_code_instruction;
            }
            Button {
                vertical-stretch: 1;
                text: verification_code + ":  " + code + " \n " + from_label + " " + from_app;
                clicked => {
                    paste-code();
                }
            }
        }
    }
}
